name: 'Latest green commit'
description: 'Fetches the latest green commit of a branch'
author: 'Raúl Juárez'
inputs:
  github_token:
    required: true
    description: 'The GitHub token to use for authentication'
  repo:
    required: true
    description: 'The GitHub repository to use in the format owner/repo'
  branch:
    required: false
    description: 'The branch to fetch the latest green commit from'
    default: 'main'
outputs:
  commit:
    description: 'The latest green commit of the branch'
runs:
  using: 'node16'
  main: 'dist/index.js'